name: Scheduled Data Upload

on:
  schedule:
    - cron: '0 5 * 12 *'  # Spustí se každý den v půlnoci EST (UTC-5) od 1. do 24. prosince

jobs:
  upload_data:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Specifikuj verzi Pythonu

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Pokud máš soubor s požadovanými balíčky

    - name: Run Python Script
      run: python your_script.py  # Nahraď "your_script.py" názvem tvého skriptu

    - name: Commit and Push Changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Scheduled data upload"
        git push
