name: Scheduled Data Upload

on:
  schedule:
    - cron: '0 5 * 12 *'

jobs:
  upload_data:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: python import_data.py

    - name: Commit and Push Changes
      run: |
        git config --global cibulect@seznam.cz
        git config --global ypsilonx
        git add .
        git commit -m "Next day to work on Python puzzles!"
        git push
